apiVersion: apps/v1
kind: Deployment
metadata:
 name: devops-case-altapay
 namespace: devops-case
spec:
 replicas: 3
 selector:
   matchLabels:
     app: altapay
 template:
   metadata:
     labels:
       app: altapay
   spec:
     containers:
     - name: altapay
       image: 147588834276.dkr.ecr.eu-central-1.amazonaws.com/devops-case-docker-ecr:case-app
       resources:
          limits:
            memory: 128Mi
            cpu: 500m
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-altapay-svc
spec:
  selector:
    app: altapay
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
