name: CI-master
on:
  push:
    branches: [ master ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --scan --no-daemon
      - name: Test
        run: ./gradlew test --tests "*"
      - name: Test Success
        if: success()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            return "\n*** Hurray basic test passed ***\n"
      - name: Test Fail
        if: failure()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: | 
            return "\n*** Dooo! basic test failed ***\n"  
  
  